- name: Add user
  ansible.builtin.user:
    name: roboshop

- name: recursively remove app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: create directory
  ansible.builtin.file:
    name: /app
    state: directory

- name: "Download {{component}} appliacation code"
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
    dest: /tmp
  
- name: "unzip {{component}} the file"
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}.zip"
    dest: /app
    remote_src: yes